### ISSUE TITLE
Проверка работы студента преподавателем

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#13]
# User Sory
Я как преподаватель хочу иметь возможность проверить работу студента после горизонтальной проверки студентами, чтобы не тратить время на указание однообразных ошибок у всех студентов.

Критерии приемки:
- Когда мы уходим на страницу "Проверка работы студента преподавателем ", пункты меню "Мои дисциплины" и "Ожидает проверки" перестают быть выделенными
- Название страницы отсутствует
- проверка работы осуществляется на одной странице.
- есть возможность просмотреть название работы
- есть возможность скачать работу
- есть возможность ввести комментарий к каждому требованию
- есть возможность написать общее замечание
- есть возможность отправить результат проверки.
- если по работе нет замечаний, то работа переходит в состояние **_"Зачтено"_**, если есть замечания, то работа переходит в статус **_"Нужно переделать"_**
- если по работе **_есть замечания_**, то все студенты, которые дали свою положительную оценку, получают **_-1 балл_** за эту работу, а если **_по работе нет замечаний_**, то студенты проверившие эту работу получают **_+1 балл_** за эту работу
# UX
Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).
[Просьба ознакомится с основными требованиями к UX](https://github.com/YuriSilenok/self-checking/blob/dev/documentation/UX.md)

### Данный UX имеет аналогичную структуру как и [ВОТ ЭТОТ](https://github.com/YuriSilenok/self-checking/issues/17)

# UI

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok, please check out this new UX

**Comment by YuriSilenok** [comment]
а вы не перепутали страницы загрузки ренения и страницу проверки работы?

**Comment by Nastasitze** [comment]
> а вы не перепутали страницы загрузки ренения и страницу проверки работы?

Перепутала, сейчас поправим
