### ISSUE TITLE
Просмотр журнала

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#14]
# User Story
Я как преподаватель, хочу иметь возможность увидеть журнал группы студентов, чтобы быстро посмотр тех, кто все сдал и не сдал для выставления аттестации, зачета, экзамена

Критерии приемки:
- На странице отображается таблица со всеми студентами в первом столбце, а последующие столбцы являются заданиями. В качестве значения столбца указывается номер задания, а при наведении на номер отображается название задания.
- Номер задания, выполненное студентом, отображается, если работа прошла все этапы проверки и была засчитана преподавателем. 
- В случае, когда у преподавателя по каким-то обстоятельствам нет студентов, на странице отображается сообщение с соответсвующим сообщением.

| Студент | ЛР01 | ЛР02 | ЛР03 |
| -------- | ------ | ------ | ------ |
| Иванов В.Д. | [2](https://github.com/YuriSilenok/self-checking/issues/14) | 3 | 4 |

- есть возможность отфильтровать по группе
- есть возможность поиска по ФИО

# UX

### Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).
![image](https://user-images.githubusercontent.com/83533847/132252667-a7099fdc-442d-4db8-9887-0e296a2167e1.png)

Страница "Журнал" имеет несколько состояний:

1) У преподавателя по какой-то причине отсутствуют студенты, закреплённые к той или иной дисциплине. Тогда на странице "Журнал" будет отображаться соответствующее сообщение - "На данный момент нет студентов, закреплённых за Вами. Отдыхайте." :
![Снимок экрана 2021-10-05 201206](https://user-images.githubusercontent.com/81413003/136075036-399da7ed-c963-40a7-a809-ea946374ecdb.png)

2) Кроме этого, даже если студенты будут назначены на преподавателя, то возможна ситуация, когда студентам не было назначено никаких задач, которые они должны выполнить. Тогда на странице "Журнал" будет отображаться соответствующее сообщение - "На данный момент студентам не было назначено никаких задачь." :
![Снимок экрана 2021-10-05 204718](https://user-images.githubusercontent.com/81413003/136075929-d7dd80e7-325a-43a2-ac90-af5ae685dafb.png)

3) Если есть студенты, то преподавателю будет доступна таблица. Таблицу можно сортировать тремя способами : 1) По ФИО;  2) По группе;  3) По ФИО && По группе.

![Снимок экрана 2021-10-05 204500](https://user-images.githubusercontent.com/81413003/136075530-11969d0f-7738-482b-af8d-0bd57f20b6fe.png)
![Снимок экрана2021-10-05 201322](https://user-images.githubusercontent.com/81413003/136075375-6d7d338a-32d6-4bf8-8f6f-7697386b2b43.png)

**Comment by Nastasitze** [comment]
@YuriSilenok  & @ValeriSavvva / Данная задача ( "Просмотр журнала" ) переносится в [План версии v*.2](https://github.com/YuriSilenok/self-checking/issues/20)

**Comment by YuriSilenok** [comment]
надо в список плана добавить эту задачу

**Comment by Nastasitze** [comment]
@YuriSilenok && @ValeriSavvva  && @IlyaTheCreator , please check out this UX. best wishes

**Comment by YuriSilenok** [comment]
А почему ты делала UX, если задача находится на User Story? User Story кто-то проверял?
