### ISSUE TITLE
Просмотр списка заданий

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#15]
# User Story
Я как студент, хочу иметь возможность просмотреть список заданий, которые необходимо выполнить, для того чтобы не искать свои задания в каждой дисциплине.

Критерии приемки:
- отображается таблица с заданиями и столбцами: Дисциплина, Тема, Задача, Статус

| Дисциплина | Тема | Задача | Статус |
| -------- | ------ | ------ | ------ |
| ТРПО | Тема №1 | [Задача №5](https://github.com/YuriSilenok/self-checking/issues/15) | Зачтено |
| ТРПО | Тема №1 | Задача №2 | Требует исправлений |

- При наведении на дисциплину появляется расшифровка аббревиатуры 
- При клике на задачу, осуществляется переход на страницу с загрузкой нового решения
- Задачи должны **_сортироваться по статусу_** в следующем порядке: Требует исправлений, Не начата, Ожидает проверки студентами, Ожидает проверки Преподавателем, Зачтено

# UX
Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

[Просьба ознакомится с основными требованиями к UX](https://github.com/YuriSilenok/self-checking/blob/dev/documentation/UX.md)

Все компоненты, находящиеся в контейнере BODY, центруются по осям ох и оу.
Страница "Просмотр списка заданий" имеет 2 основных состояния:
### 1 : На данный момент у преподавателя или студента нет работ, которые нужно проверить или сделать.

В этом случае на сайте вместо таблицы появляется сообщение:
![2021-09-01_11-04-32](https://user-images.githubusercontent.com/81413003/131635699-8a0534a6-c1d6-4beb-9a48-885ede475a4b.png)

###  2 : Работы есть.
В этом случае на странице появляется таблица:
![2021-07-23 (9)](https://user-images.githubusercontent.com/81413003/126785952-458e0f64-6c15-4d2d-8930-1e1569a8a69d.png)

![2021-07-23 (10)](https://user-images.githubusercontent.com/81413003/126786365-ece6a37f-1cf0-49db-822b-139bb994012d.png)

# UI

![Image](https://user-images.githubusercontent.com/83533847/128466562-9d16563d-dedf-48f5-af6d-f97accfd6150.png)
![2021-09-01_11-03-57](https://user-images.githubusercontent.com/81413003/131635761-e6b9a358-481b-402e-a28d-e47075d77e70.png)

*При наведении на дисциплину появляется полное наименование дисциплины.
### ДОБАВЛЕНИЕ НОВЫХ РАБОТ
При добавление новых работ отцентрованная по середине таблица расширяется вниз ( добавление новых строк ). 
Когда длина ( ось оу ) таблице будут больше длины дисплея, то появится скрол вниз.

**Comment by Nastasitze** [comment]
@ValeriSavvva  & @YuriSilenok , pleas check new UX

**Comment by ValeriSavvva** [comment]
Все отлично

**Comment by YuriSilenok** [comment]
пойдет

**Comment by ValeriSavvva** [comment]
@YuriSilenok @Nastasitze

**Comment by Nastasitze** [comment]
> @YuriSilenok @Nastasitze

All ok

**Comment by YuriSilenok** [comment]
Немного напрягает выравнивание в таблице по центру, так как смотрится это красиво только когда длинна строк в ячейках одинаковое. Если это только у меня одного так, то посмотрим что получится по итогу, когда задач будет много. А так норм.

**Comment by ValeriSavvva** [comment]
Верстку можно будет проверять только после мержа ветки 49, так как там все нужные стили.
