### ISSUE TITLE
Загрузка решения на проверку

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#16]
# User Story
Я как студент, хочу иметь возможность загружать решение на проверку, для того чтобы не показывать их лично и проверка происходила быстрее.

Критерии приемки:
- Загрузка работы возможна, если задача находится **_не в состоянии "Зачтено"_**
- Максимальный объем загружаемого файла определяется в задаче
- Загрузка файлов возможна только zip форматов
- На странице отображается история загрузки предыдущих решений в виде таблицы:
    - Загружено
    - Кол-во проверок
    - Замечание
- После загрузки файла, статус задачи устанавливается на **_"Ожидается проверки студентом"_**
- Если пользователь "Преподаватель" по какой-то причине не указал требования к проверки к той или иной задаче, то контейнера, где должны отображаться требования, не будет
- При отсутствии истории загрузки на экране будет отображаться сообщении с соответствующей информацией: "Решение на данное задание ещё не отправлялось на проверку."

# UX
Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

[Просьба ознакомится с основными требованиями к UX](https://github.com/YuriSilenok/self-checking/blob/dev/documentation/UX.md)

### 1) Задача не имеет списка требований, и история загрузки решений пуста (это первая загрузка решения студентом).
![2021-07-30_15-58-48](https://user-images.githubusercontent.com/81413003/127656580-bfcc7420-449d-4d43-9688-5219f3e11f7c.png)

### 2) У задачи есть список требований, и история загрузки решений пуста (это первая загрузка решения студентом):
![2021-07-30_15-59-38](https://user-images.githubusercontent.com/81413003/127657083-08d8b825-af73-4caf-ac2b-8db2ff41c65c.png)

### 3) Задача имеет список требований, и история загрузки решений не пуста.
![2021-07-30_16-44-29](https://user-images.githubusercontent.com/81413003/127662156-d432da2a-9f31-487a-bb0b-b32c7f7f9df6.png)

# UI
![2021-08-17_15-23-32](https://user-images.githubusercontent.com/81413003/129725739-8ea6cc1a-7f3b-44ac-8d98-e63d8c60c648.png)
![2021-08-17_15-23-48](https://user-images.githubusercontent.com/81413003/129725773-a706f190-1637-4812-ab2c-e463da1e328d.png)
![2021-08-17_15-24-25](https://user-images.githubusercontent.com/81413003/129725815-7aae3355-ca00-4b66-8ac3-1f1889ae9a4a.png)

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok, please check out this new UX

**Comment by YuriSilenok** [comment]
Почему на UX в истории решений третий столбец называется **проверки**, в US другое требование.

**Comment by YuriSilenok** [comment]
> * Название страницы отсутствует

у нас на это должны быть отдельные требования. @Nastasitze оформи их в требовнаиях к UX

**Comment by YuriSilenok** [comment]
> > * Название страницы отсутствует
> 
> у нас на это должны быть отдельные требования. @Nastasitze оформи их в требовнаиях к UX

оформлять нужно через ветку issue-16, так как уже здесь я официальнос делал запрос на добавление это в документацию

**Comment by YuriSilenok** [comment]
> * Когда мы находимся на странице "Загрузка решений на проверку", пункты меню "Мои дисциплины" и "Ожидает проверки" перестают быть выделенными

это требование к хэдеру, которое должно быть оформлено в UI, да @ValeriSavvva ?

**Comment by Nastasitze** [comment]
> > > * Название страницы отсутствует
> > 
> > 
> > у нас на это должны быть отдельные требования. @Nastasitze оформи их в требовнаиях к UX
> 
> оформлять нужно через ветку issue-16, так как уже здесь я официальнос делал запрос на добавление это в документацию

То есть, я прописываю это требование в issue-16, то есть тут, в разделе UX
А требование по поводу header будет прописано в разделе UI
?

**Comment by Nastasitze** [comment]
@YuriSilenok  & @ValeriSavvva, please check out new UI/ Есть один вопрос на размышление:  на 1 картинке UI был добавлен элемент - textbox ("Пока эта задача ..."), который отсутствует на первоначальном UX. Вопрос: оставляем этот блок и правим UX, или убираем этот новый элемент и правим UI?

**Comment by YuriSilenok** [comment]
Я думаю стоит оставить предупреждение об отсутствии требований к задаче. 
P.S. textbox - поле ввода, label - какая-то надпись. так что это label

**Comment by Nastasitze** [comment]
@ValeriSavvva  & @YuriSilenok  , изменён UI (ситуация, когда требования ещё не созданы) в соответствии с UX.

**Comment by ValeriSavvva** [comment]
@YuriSilenok  напомните какую мне кнопку оставлять декоративную или открывающую проводник?
![image](https://user-images.githubusercontent.com/83533847/132492466-f80a2ff5-6ef2-4b07-a28c-59bf95b8a947.png)

**Comment by YuriSilenok** [comment]
Нужно оставить ту, в которой возможно реализовать UI
