### ISSUE TITLE
Проверка работы студента студентом

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#17]
# User Story
Я как студент хочу иметь возможность проверить работу студента, чтобы получить баллы по заданию и ее завершению.

Критерии приемки:
- Есть возможность скачать архив с решением
- Есть возможность написать комментарий к каждому требованию
- Есть возможность написать общее замечание
- Есть возможность отправить результаты проверки
---
- Если **_есть замечания_** по работе, то задача должна перейти в статус "Требуются исправлений"
- Если **_нет замечаний_**, то решению добавляется одна положительная проверка
- Если **_положительных проверок недостаточно_** для проверки преподавателем, то задача остается в состоянии "Ожидает проверки студентом", иначе в состоянии "Ожидает проверки преподавателем"
# UX
Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).
[Просьба ознакомится с основными требованиями к UX](https://github.com/YuriSilenok/self-checking/blob/dev/documentation/UX.md)

### 1. Ситуация: пользователь "Преподаватель" при каких-то обстоятельствах забыл добавить требования, или изначально задача не подразумевала требования, тогда пользователь "Стедент" увидит в контейнере, где должны располагаться данные требования, сообщение с информацией об этом:
![2021-08-10_16-13-39](https://user-images.githubusercontent.com/81413003/128874183-e621919c-2376-4a5b-a6f1-7efbe9f6ddc8.png)

### 2. Ситуация: пользователь "Преподаватель" создал требования, которые располагаются в отдельном контейнере:
![2021-08-09 (4)](https://user-images.githubusercontent.com/81413003/128875382-cee7bd08-78bb-464a-a06d-22bdd2bc699e.png)

### По мере заполнения textboxes, находящимися напротив каждого требования, они будут расширятся, при этом другие требования и соответствующие им textboxes сдвигаются вниз,  расширяя контейнер, в котором они находятся:
![2021-08-09 (1)](https://user-images.githubusercontent.com/81413003/128876013-931397b3-12c5-4065-904d-cc7223a3bdcd.png)

### Поведение Textbox "Общее замечание". При заполнении данного поля элемент Textbox расширяется вниз, расширяя контейнер в котором он находится:
![2021-08-09 (3)](https://user-images.githubusercontent.com/81413003/128876476-ee47e79e-d1bc-4d2b-852a-12a92d016004.png)
 
# UI

![image](https://user-images.githubusercontent.com/83533847/132367334-6e3dda25-1fd2-4c34-9bb9-3ae2d031bc6d.png)
![image](https://user-images.githubusercontent.com/83533847/132367338-1bcf6042-db2a-4b76-9849-3bd460ff1d34.png)

**Comment by Nastasitze** [comment]
@ValeriSavvva  & @ValeriSavvva , please check out this UX

**Comment by ValeriSavvva** [comment]
норм

**Comment by YuriSilenok** [comment]
отлично

**Comment by ValeriSavvva** [comment]
@YuriSilenok  @Nastasitze

**Comment by YuriSilenok** [comment]
Названия дочерних страниц у нас выравниваются по центру.

**Comment by Nastasitze** [comment]
@ValeriSavvva . all ok
