### ISSUE TITLE
[CF] Не авторизовывается для входа на сайта.

### ISSUE THREAD

**Issue by chosen44** [YuriSilenok/self-checking#19]
1) Заходим тина сайт через учетную запись другого студента
2) На главной странице в левом верхнем углу нажимаем на раздел: "Нужно проверить"
3) Нажимаем на ссылку в строке: "Команды" 
4) Скачиваем файл с лабораторной работой для проверки
Ожидаемый результат: Студент зашел на сайт
Фактический результат: Не возможности авторизоваться, т.к. при вводе адреса эл. почты и пароля, ничего не происходит. 	

Дополнения: https://drive.google.com/file/d/1oo9jiQvn8DK7Gngz4hu9rPcXGW4JN4IS/view?usp=sharing

**Comment by YuriSilenok** [comment]
> * Заходим тина сайт через учетную запись другого студента
> * На главной странице в левом верхнем углу нажимаем на раздел: "Нужно проверить"
> * Нажимаем на ссылку в строке: "Команды"
> * Скачиваем файл с лабораторной работой для проверки
>   Ожидаемый результат: Студент зашел на сайт
>   Фактический результат: Не возможности авторизоваться, т.к. при вводе адреса эл. почты и пароля, ничего не происходит.

нужно дать название этому списку

**Comment by YuriSilenok** [comment]
> Дополнения: https://drive.google.com/file/d/1oo9jiQvn8DK7Gngz4hu9rPcXGW4JN4IS/view?usp=sharing

вся информация должна быть в задаче, и не должна вести на сторонние ресурсы

**Comment by YuriSilenok** [comment]
почему казана в заголовке `[CF]`?

**Comment by YuriSilenok** [comment]
Не правильно развернута тестовое окружение
