### ISSUE TITLE
[LF] Не отображается ссылка скачать файл на странице проверки работы

### ISSUE THREAD

**Issue by chosen44** [YuriSilenok/self-checking#2]
Scenario:
1. Войти как студент/преподаватель
2. Открыть страницу для проверки работы
**Ожидаемый результат:** Отображается ссылка "скачать" для архива с решением студента
**Фактический результат:** Ссылка не отображается
![скрин бага](https://user-images.githubusercontent.com/14871471/123928769-dfeb6580-d996-11eb-89f1-886e9fc119d9.png)

Обходной путь:
1.
2.

**Comment by YuriSilenok** [comment]
Исправлено в версии v0.4.2.1

**Comment by chosen44** [comment]
Ссылка: "скачать файл" на странице проверки работы в весрии S0V0.1 - отображается.

**Comment by YuriSilenok** [comment]
> в весрии S0V0.1 - отображается.

Как вы определили что, то что вы тестировали было этой версии?
