### ISSUE TITLE
UX для страницы "Авторизация пользователя"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#23]
### UX для страницы "Авторизация пользователя".
Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-13 (18)](https://user-images.githubusercontent.com/81413003/125459323-b525cf8c-3dfe-4883-822b-cd06c88ace55.png)

---
# Ссылки
User Story #6

**Comment by Nastasitze** [comment]
**Version 1**
> _( 02.07.2021 )_

![Страницы-Authorization  US-2  #6](https://user-images.githubusercontent.com/81413003/124285852-0526d200-db57-11eb-8fc6-24a58e565fcb.png)

**Comment by YuriSilenok** [comment]
В описание задачи

**Comment by Nastasitze** [comment]
Проверьте на адекватность макет @YuriSilenok  & @ValeriSavvva.
thank u for ur attention

**Comment by YuriSilenok** [comment]
Ни кто не проверил

**Comment by Nastasitze** [comment]
проверка @Nastasitze

**Comment by YuriSilenok** [comment]
я так же не понимаю, зачем нам контейнер вверху страницы. Изходя из чего он там появился, есть какие-то требования которые побудили его там создать?

**Comment by ValeriSavvva** [comment]
@YuriSilenok, Настя поясняла свои уже обьясняла это тем, что она вполне не может представитть как будет выглядить сама регистрация с дизайном и изначально наш UX предполагал не само расположение объектов как главную цель, а скорее наличие конкретных нужных частей макета, которые 100% должны существовать, что бы мне в ходе UI разработке можно было не только менять формы и цвета, но и расположение если угодно, и для этого мне будет нужно только знать, что должно быть ТОЧНО чтобы не потерять.

**Comment by ValeriSavvva** [comment]
@YuriSilenok а кстати да, там внизу подписано что контент плэйс из себя представляет "Content place - располагаются логотип или иные элементы дизайна" P.S. пояснительная бригада

**Comment by ValeriSavvva** [comment]
Все хорошо

**Comment by YuriSilenok** [comment]
> * иные элементы дизайна;

@ValeriSavvva у тебя есть иде, какие элементы дизайна ты поместишь на страница авторизации?

**Comment by YuriSilenok** [comment]
видимо я жду новый UX

**Comment by Nastasitze** [comment]
@ValeriSavvva  & @YuriSilenok , посмотрите такой вариант.

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok , посмотрите такой вариант. Подправила прототип: добавила контейнер для названия, чтобы структура соответствовала Регистрации. @ValeriSavvva, нужен тебе этот контейнер или заголовок будет помёщен в общий контейнер ( Body )?

**Comment by YuriSilenok** [comment]
мне норм

**Comment by Nastasitze** [comment]
Утверждается ли данный вариант как итоговый ? @YuriSilenok  @ValeriSavvva

**Comment by ValeriSavvva** [comment]
кроасиво

**Comment by YuriSilenok** [comment]
меня все устраивает
эта задача стала частью задачи #57
