### ISSUE TITLE
UX страницы "Регистрация пользователя"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#24]
### UX для страницы "Регистрация нового пользователя"
Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-13 (19)](https://user-images.githubusercontent.com/81413003/125459488-9447341f-88d7-4f3b-b547-4bd3ad04ef9f.png)

# Ссылки
User Story #5 

---
 # Срок
 06.07.2021

**Comment by Nastasitze** [comment]
Проверьте на адекватность макет @YuriSilenok  & @ValeriSavvva. 
thank u for ur attention

**Comment by YuriSilenok** [comment]
Воу, кажется клммент не сработал, давай без проверки не будем закрывать

**Comment by Nastasitze** [comment]
Требует проверки UX для страницы "Авторизация пользователя".
@ValeriSavvva & @YuriSilenok , проверьте, пожалуйста, на содержание страницы.

**Comment by YuriSilenok** [comment]
- в первой версии ПО вы договорились что регистрация будет только для студентов, нам нужны эти радиобатоны сейчас?
- разделив ФИО и прочее на блоки у которых нет заголовков, мы что-то этим обозначаем?

**Comment by ValeriSavvva** [comment]
@YuriSilenok 
- мы хотели сделать два батона студент и преподаватель

- абсолютно ничего не обозначает

**Comment by YuriSilenok** [comment]
> @YuriSilenok
> 
> * мы хотели сделать два батона студент и преподаватель
> * абсолютно ничего не обозначает

это был предпоследний раз когда мы созванивались. @Nastasitze отразите это в User Story

**Comment by YuriSilenok** [comment]
> @YuriSilenok
> 
> * мы хотели сделать два батона студент и преподаватель
> * абсолютно ничего не обозначает

а почему вы отвечаете, вы делали этот UX?

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok , посмотрите такой вариант. Фио могу разделить на отдельные строки с textboxes.

**Comment by YuriSilenok** [comment]
Почему заголовок "Регистрация" в отдельном контейнере, а у авторизации не так?

**Comment by YuriSilenok** [comment]
мне норм

**Comment by ValeriSavvva** [comment]
Мы договаривались что не будет ФИО и оставим батоны, не рассматривая случая студент-препод.

**Comment by ValeriSavvva** [comment]
А так все верно

**Comment by Nastasitze** [comment]
UX страницы "Регистрация пользователя" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант.  Исключала поле ввода ФИО, добавила radio-button для студента.

**Comment by YuriSilenok** [comment]
> Мы договаривались что не будет ФИО и оставим батоны, не рассматривая случая студент-препод.

Мы договорились не отображать фио в хэдере, как преподаватель студентов то будет добавлять, как журнал просматривать, это жутко неудобно будет

**Comment by YuriSilenok** [comment]
> Мы договаривались что не будет ФИО и оставим батоны, не рассматривая случая студент-препод.

зачем нам батон оставлять, тем более из одного варианта?

**Comment by YuriSilenok** [comment]
мне норм

**Comment by ValeriSavvva** [comment]
Говно, переделывай!

**Comment by Nastasitze** [comment]
Бро
это переделанный варик

**Comment by ValeriSavvva** [comment]
красотаааааааааааа
