### ISSUE TITLE
UX для страницы "Нужно проверить"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#25]
### UX для страницы Преподавателя:

Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-13 (17)](https://user-images.githubusercontent.com/81413003/125456220-37e87757-4513-49de-b4b4-67ad2e3d9595.png)

### UX для страницы Студента:

![2021-07-13 (16)](https://user-images.githubusercontent.com/81413003/125455985-86ee4634-14e8-472f-8bf5-c7ee53ada199.png)

---
# Ссылки
User Story #34

**Comment by Nastasitze** [comment]
Требует проверки UX для страницы "Нужно проверить".
@ValeriSavvva & @YuriSilenok , проверьте, пожалуйста, на содержание страницы.

**Comment by YuriSilenok** [comment]
мне кажется что контейнер вверху, это пустая трата места, у нас нет даже идей о том, что мы там будем отображать, тем более в первой версии

**Comment by YuriSilenok** [comment]
Жду новую версию UX

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok , посмотрите такой вариант.

**Comment by YuriSilenok** [comment]
А что означает номер в этой таблице и зачем он тому, кто будет проверять эту работу?

**Comment by Nastasitze** [comment]
UX для страницы "Нужно проверить".
@ValeriSavvva & @YuriSilenok ,посмотрите такой вариант. Убрала нумерацию для строк.

**Comment by YuriSilenok** [comment]
Почему в таблице у задачи есть слово название, а у темы и дисциплины нет?

**Comment by YuriSilenok** [comment]
Исходя из каких требований появился пункт меню "журнал" ?

**Comment by Nastasitze** [comment]
В требованиях это не прописано, но такая навигация упрощает использование сайта, так как в любой момент пользователь может перейти в любую вкладку.

**Comment by ValeriSavvva** [comment]
красиво

**Comment by YuriSilenok** [comment]
перенесено в #34
