### ISSUE TITLE
UX для страницы "Проверка работы"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#26]
### UX для страницы "Проверка работы" 
Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-14 (8)](https://user-images.githubusercontent.com/81413003/125636630-57e9072c-2002-4ecb-a52b-cf0bed378a2a.png)

---
# Ссылки
User Story #13

**Comment by YuriSilenok** [comment]
инструкция в большое поле

**Comment by Nastasitze** [comment]
@YuriSilenok @ValeriSavvva , look at this variant.

**Comment by ValeriSavvva** [comment]
найс

**Comment by YuriSilenok** [comment]
перенесено в #13
