### ISSUE TITLE
UX для страницы "Мои задания"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#27]
### UX для страницы "Мои задания"

Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-14 (7)](https://user-images.githubusercontent.com/81413003/125634285-25789882-7585-4892-927b-90ac38436cc3.png)

---
# Ссылки
User Story #15

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok , посмотрите такой вариант.

**Comment by YuriSilenok** [comment]
тот же вопрос, что значит номер и зачем он студенту?

**Comment by Nastasitze** [comment]
UX для страницы "Мои задания" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант. Убрала нумерацию требований.

**Comment by YuriSilenok** [comment]
убрать сортировку и добавление

**Comment by ValeriSavvva** [comment]
красиво

**Comment by Nastasitze** [comment]
@YuriSilenok look at this variant.

**Comment by ValeriSavvva** [comment]
мурчашно

**Comment by YuriSilenok** [comment]
перенесено #15
