### ISSUE TITLE
UX для страницы "Загрузить решение"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#28]
**UX для страницы "Загрузить решение"**

Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-15 (4)](https://user-images.githubusercontent.com/81413003/125771466-54af4429-4f66-49ba-9977-ef409ef14b01.png)

---
# Ссылки
User Story #16

**Comment by Nastasitze** [comment]
UX страницы "Загрузить решение" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант. Исключала поле ввода ФИО, добавила radio-button для студента.

**Comment by YuriSilenok** [comment]
да вроде норм. конечно требований может быть много по одной ЛР, но там посмотрим.

**Comment by Nastasitze** [comment]
В зависимости от кол-ва требований контейнер будет увеличиваться. @ValeriSavvva, do like this version.

**Comment by YuriSilenok** [comment]
да, конечно будет, вопрос как это будет выглядеть когда их будет 20-30 штук

**Comment by Nastasitze** [comment]
UX для страницы "Список требований" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант. Изменила композицию компонентов.

**Comment by YuriSilenok** [comment]
название страницы

**Comment by YuriSilenok** [comment]
студент сначала выбирает работу, а через страницу с работой загружает решение

**Comment by ValeriSavvva** [comment]
выпадающий список у названия делит

**Comment by Nastasitze** [comment]
@YuriSilenok  @ValeriSavvva  look at he this variant.

**Comment by YuriSilenok** [comment]
Перенесено в #16
