### ISSUE TITLE
UX для страницы "Мои дисциплины"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#29]
### UX для страницы "Мои дисциплины"
Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-15 (2)](https://user-images.githubusercontent.com/81413003/125770219-9ad6aee5-449d-405f-8552-08bc3564a75f.png)

---
# Ссылки
User Story #7

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok , посмотрите такой вариант.

**Comment by YuriSilenok** [comment]
что означает номер и зачем он преподавателю?

**Comment by Nastasitze** [comment]
UX для страницы "Мои дисциплины" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант. Убрала нумерацию.

**Comment by YuriSilenok** [comment]
Мне кажется нам не хватает отдельной задачи на хедер и меню. Мне помнится вы хотели что бы хедер был, а под ним меню. Или я ошибаюсь?

**Comment by YuriSilenok** [comment]
Сейчас на журнал ссылка в хэдере и в таблице.

**Comment by YuriSilenok** [comment]
плюсы на добавить

**Comment by YuriSilenok** [comment]
название страницы

**Comment by ValeriSavvva** [comment]
Красиво

**Comment by Nastasitze** [comment]
@YuriSilenok look at this variant.

**Comment by ValeriSavvva** [comment]
мяучашно

**Comment by Nastasitze** [comment]
@YuriSilenok @ValeriSavvva  look at this variant.

**Comment by ValeriSavvva** [comment]
замурчашно

**Comment by YuriSilenok** [comment]
перенесено в #49
