### ISSUE TITLE
План версии v0.1

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#3]
# Подзадачи

- #47
- #48
- #49
- #50
- #51
- #52
- #13 
- #17 
- #34 
- #15 
- #16 
- #62 

---

# Переходы между страницами.
![Страницы-Карта](https://user-images.githubusercontent.com/14871471/124234407-a9d7ee00-db1c-11eb-9a6c-060319e703d7.png)
[Текущая версия
](https://drive.google.com/file/d/1ACG9kTcY8k_KHIysRzqSjRYsUgWgJCeQ/view?usp=sharing)
# Прототип

[Текущая версия](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10)

---

# Общие требования к макету #21
# Общие требования к дизайну #22

---

[ERD](https://drive.google.com/file/d/1oZuyPfy40A1k8cG-4t6qGJ0O5u_OflCk/view?usp=sharing)

---

# Приемочный тест
Действие пользователя | Ответ системы
--- | ---
На странице регистрации Студент1 вводит email, ФИО, пароль и подтверждение пароля | Система регистрирует пользователя как студента и авторизует его. После авторизации пользователя отображается страница "Нужно проверить"
Студент1 нажимает кликает по кнопке Logout | Отображается страница авторизации
Преподаватель переходит в меню "Список дисциплин" | Отображается список дисциплин
Преподаватель вводит название дисциплины и кликает кнопку Добавить | Отображается страница со списком тем, для созданной дисциплины
Преподаватель вводит название темы и кликает на кнопку Добавить | Отображается страница со списком заданий, для созданной темы
Преподаватель вводит название задания, прикрепляет ссылку на задание, указывает количество проверок студентами  кликает по кнопке Добавить | Отображается страница со списком требований к созданному заданий
Преподаватель вводит описание требования и кликает по кнопке Добавить | Отображается страница со списком требований для созданного ранее задания в которой присутствует созданное требование
Преподаватель кликает в меню на "Список дисциплин" | Отображается созданная ранее дисциплина в списке дисциплин
Преподаватель кликает на название дисциплины | Отображается страница со списком тем для выбранной дисциплины, в списке присутствует ранее созданная тема. В списке студентов отображаются только те студенты, на которых не назначена дисциплина.
В блоке "Добавить студента к дисциплине" в выпадающем списке выбирает группу  | В выпадающем списке "Студенты" отображаются только те студенты, которые принадлежат выбранной группе.
В выпадающем списке "Студенты" выбрать студента0,1,2,3,4,5 и кликнуть на кнопку Добавить | Студент0,1,2,3,4,5 больше не отображается в списке студенты
Кликнуть на кнопку Logout | Отображается страница авторизации
Авторизоваться как ранее зарегистрированный студент1 | Отображается страница "Нужно проверить"
Кликнуть в меню на "Мои работы" | Отображается задания из ранее добавленной дисциплины,, у всех заданий статус "Не начата"
Кликнуть по названию работы | Отображается страница с работой, в которую можно загрузить файл с решением задания
Студент1 прикрепляет архив ZIP | В блоке "История решений" появляется новая запись, в которой количество проверок = 0
Студент1 кликает на кнопку Logout | Отображается страница авторизации
Кликнуть на кнопку Зарегистрироваться | Отображается страница "Регистрация пользователя"
Регистрируется студент2, студент3, студент4, студент5, студент6 | Отображается страница "Нужно проверить", в ней нет заданий которые нужно проверить
Студент2,3,4,5,6 кликает на кнопку Logout | Отображается страница "Авторизация пользователя"
Преподаватель авторизуется | Отображается страница "Нужно проверить"
Преподаватель кликает в меню "Мои дисциплины" и кликает по названию ранее созданной дисциплине | Отображается страница со списком тем
Преподаватель добавляет для студента2,3,4,5,6 дисциплину и кликает на кнопку Logout | Отображается страница авторизации
Студент2,3,4,5,6 авторизуется | отображается страница "Нужно проверить"
Студент2,3,4,5,6 кликает по названию задания | отображается страница проверки решения
Студент2 пишет замечание к требованию и кликает по кнопке "Отправить" |  Отображается страница нужно проверить, проверенная работа на странице не отображается
Студент1 авторизуется и кликает в меню "Мои работы" | Отображается страница "Мои задания", работа по которой было дано замечание имеет статус "Требует исправлений"
Студент1 кликает на название задания со статусом "Требует исправления" | В истории решений появилась ссылка "замечание"
Студент 1 кликает на ссылку "Замечание" | Отображается страница с замечанием
Студент1 загружает новый zip архив с исправлениями | В истории решений появляется новая строка, статус задания меняется на "Ожидает проверки студентом"
Студент2,3,4,5,6 дают положительную проверку задания | Задание не отображается в списке на странице "Нужно проверить"
Преподаватель авторизуется | На странице "Нужно проверить" отображается одобренная студентами работа
Преподаватель переходит к проверке работы, пишет общее замечание, кликает кнопку Отправить  | В списке "Нужно проверить" задание не отображается. Каждый студент, который проверял работу, получает -1 балл за работу.
Студент1 авторизуется и переходит на страницу "Мои задания" | Статус задания "Требуются исправлений"
Студент2,3,4,5,6 авторизуются, кликают в меню на "Мои работы" | На странице "Мои работы" 0 баллов сменилось на -1 у проверяемого задания
Студент1 отправляет новое решение, студент2,3,4,5,6 и преподаватель дают положительную проверку | На странице "Нужно проверить" работа не отображается. У студента1 отображается статус задания "Зачтено"
Студент2,3,4,5,6 кликают в меню "Мои задания" | На станице "Мои работы" -1 баллов за задание сменилось на 0 баллов
Студент 1 и преподаватель проверяет работы студентов2,3,4,5,6 без замечаний | После пяти проверок работ студентом1 и преподавателем, у студента1 в задании в место числа отображается зачтено (первое зачтено за сданную работу, второе зачтено за 5 правильных проверок)

**Comment by YuriSilenok** [comment]
@Nastasitze @ValeriSavvva 
Посмотрите на этот список, все ли здесь есть то что нужно сделать в первую очередь и нет ли здесь чего-то лишнего

**Comment by Nastasitze** [comment]
Убрала из списка задачу #14 : она не входит список задач 1-ой version
