### ISSUE TITLE
UX для страницы "Список тем"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#31]
### UX для страницы "Список тем"

Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-15](https://user-images.githubusercontent.com/81413003/125767669-61b73d5b-1ffb-4cf2-a168-8834a9452e27.png)

---
# Ссылки
User Story #8

**Comment by Nastasitze** [comment]
UX для страницы "Список тем" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант.

**Comment by YuriSilenok** [comment]
а где будет кнопка добавления студента к дисциплине, а еще нужно обозначить что за выпадающие списки

**Comment by Nastasitze** [comment]
UX для страницы "Список требований" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант. Добавила кнопку для добавления студента. Добавила обозначения "Группа", "ФИО" при добавлении студента.

**Comment by YuriSilenok** [comment]
+-добавить

**Comment by YuriSilenok** [comment]
ткмы

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok , посмотрите такой вариант.

**Comment by ValeriSavvva** [comment]
красиво

**Comment by Nastasitze** [comment]
@YuriSilenok @ValeriSavvva  , look at this variant.

**Comment by ValeriSavvva** [comment]
мурчативно

**Comment by YuriSilenok** [comment]
перенесено в #50
