### ISSUE TITLE
UX для страницы "Список заданий"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#32]
### UX для страницы "Список заданий"

Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-14 (1)](https://user-images.githubusercontent.com/81413003/125630956-343e62af-6928-46bd-b551-309a84267e12.png)

---
# Ссылки
User Story #9

**Comment by Nastasitze** [comment]
UX для страницы "Список заданий" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант.

**Comment by YuriSilenok** [comment]
зачем преподавателю этот номер в таблице?

**Comment by Nastasitze** [comment]
UX для страницы "Список требований" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант. убрала нумерацию заданий.

**Comment by YuriSilenok** [comment]
мне норм

**Comment by ValeriSavvva** [comment]
красиво

**Comment by Nastasitze** [comment]
@YuriSilenok look at this variant.

**Comment by ValeriSavvva** [comment]
мяукательно

**Comment by YuriSilenok** [comment]
перенесено в #51
