### ISSUE TITLE
UX для страницы "Список требований"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#33]
### UX для страницы "Список требований"

Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

![2021-07-14 (4)](https://user-images.githubusercontent.com/81413003/125631726-76047e53-1e03-43fe-a8c9-f33c7fa39dd8.png)

---
# Ссылки
User Story #10

**Comment by Nastasitze** [comment]
UX для страницы "Список требований" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант.

**Comment by YuriSilenok** [comment]
зачем здесь номер в таблице?

**Comment by Nastasitze** [comment]
UX для страницы "Список требований" @ValeriSavvva & @YuriSilenok , посмотрите такой вариант. убрала нумерацию требований.

**Comment by YuriSilenok** [comment]
Требование-требования

**Comment by ValeriSavvva** [comment]
красиво

**Comment by ValeriSavvva** [comment]
Настя, все по красоте

**Comment by Nastasitze** [comment]
@YuriSilenok look at he this variant.

**Comment by ValeriSavvva** [comment]
замурчательно

**Comment by YuriSilenok** [comment]
перенесено #52
