### ISSUE TITLE
Просмотр списка "Ожидает проверки"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#34]
я как студент/преподаватель хочу иметь возможность просматривать список решений, которые нужно проверить, для того чтобы набрать баллы по заданию/не искать решения работы

Критерии приемки:
- Список отображает атрибуты: Дисциплина, Тема, Название задания

| Дисциплина | Тема | Название задачи |
| -------- | ------ | ------ | 
| ТРПО | Тема №1 | [Какая-то задача №1](https://github.com/YuriSilenok/self-checking/issues/34) |
| ТРПО | Тема №1 | Какая-то задача №2 | 

- При клике по названию задания осуществляется перед на страницу проверки решения
- При наведении на дисциплину появляется расшифровка аббревиатуры 
- Список сортируется в хронологическом порядке: от самых старых, до самых свежих.
- Для проверяющего студента отображаются работы подходящие под следующие критерии:
  - Студенту было выдано такое задание
  - Студент не получил нужного количества баллов по этой работе за проверку работ.
- Для преподавателя:
  - Преподаватель создал эту дисциплину
- Название страницы не отображается. Вместо этого надпись "Ожидает проверки" имеет шрифт bold

# UX
Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).
[Просьба ознакомится с основными требованиями к UX](https://github.com/YuriSilenok/self-checking/blob/dev/documentation/UX.md)

Все компоненты, находящиеся в контейнере BODY, центруются по осям ох и оу.
Страница "Нужно проверить"  (и для преподавателя, и для студента) имеет 2 основных состояния:
### 1 : На данный момент у преподавателя или студента нет работ, которые нужно проверить или сделать.

В этом случае на сайте вместо таблицы появляется сообщение:

![2021-07-22](https://user-images.githubusercontent.com/81413003/126613335-541e2343-9a36-4a2d-b21c-b869584b0e68.png)

###  2 : Работы есть.
В этом случае на странице появляется таблица:

![2021-07-22 (1)](https://user-images.githubusercontent.com/81413003/126613433-337d7963-428a-41c0-be53-0c24e06c19d6.png)

*При наведении на дисциплину появляется полное наименование дисциплины:
![2021-07-20 (1)](https://user-images.githubusercontent.com/81413003/126282663-129094fe-6eaf-4ed6-959e-96dabcc9af0d.png)

### ДОБАВЛЕНИЕ НОВЫХ РАБОТ
При добавление новых работ отцентрованная по середине таблица расширяется вниз ( добавление новых строк ). 
Когда длина ( ось оу ) таблице будут больше длины дисплея, то появится скрол вниз.

# UI 
### 1 : На данный момент у преподавателя или студента нет работ, которые нужно проверить или сделать.
![image](https://user-images.githubusercontent.com/83533847/126605120-b9c05139-e2c7-4f2c-bda1-8980b1ec69e2.png)

###  2 : Работы есть. В этом случае на странице появляется таблица:
![image](https://user-images.githubusercontent.com/83533847/126614895-816b4b1a-7d53-49de-b337-be61457178ed.png)

###  3 : Работы есть  и их количество больше, чем количество, которое может поместиться на экране. В этом случае на странице появляется таблица:
![image](https://user-images.githubusercontent.com/83533847/126614848-ff431a37-1dbf-43e7-b4ab-82c662ba5b63.png)

**Comment by Nastasitze** [comment]
@YuriSilenok & @ValeriSavvva  please check new US , UX

**Comment by YuriSilenok** [comment]
В ширина столбцов будет всегда одинаковая?

**Comment by Nastasitze** [comment]
> В ширина столбцов будет всегда одинаковая? 

Да, просто я тупанула, когда расширяла контейнер с Body

**Comment by YuriSilenok** [comment]
мы решили что у страниц будет отображается название страницы. Мы это зафиксировали в UX? Это UX не имеет название страницы.

**Comment by Nastasitze** [comment]
> мы решили что у страниц будет отображается название страницы. Мы это зафиксировали в UX? Это UX не имеет название страницы.

Я основывалась на результате голосования ![image](https://user-images.githubusercontent.com/81413003/126445817-5dba0f52-6437-4ef5-bcd9-de270572ff80.jpeg)

Или они не действительны? @ValeriSavvva @YuriSilenok

**Comment by YuriSilenok** [comment]
Действительны, видимо я что-то перепутал.

**Comment by ValeriSavvva** [comment]
Все так

**Comment by ValeriSavvva** [comment]
@Nastasitze @YuriSilenok  ожидаю замечаний

**Comment by Nastasitze** [comment]
@ValeriSavvva , Лер, может сделать ширину строк побольше или текст уменьшить, чтобы лучше читалось ? А так по остальному i dont have any questions

**Comment by ValeriSavvva** [comment]
поменяла на 18 шрифт

**Comment by Nastasitze** [comment]
nice, i agree with everything
