### ISSUE TITLE
Дизайн страницы "Регистрация пользователя"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#36]
# Исправленный безальтернативный вариант регистрации
![image](https://user-images.githubusercontent.com/83533847/125486366-ef2a0941-4ec6-418c-872a-a8e43ac14765.png)

# Ссылки
План #3 
User Story #5 
Макет #24

---
 # Срок
 07.07.2021

**Comment by Nastasitze** [comment]
Я согласна со всем

**Comment by YuriSilenok** [comment]
все норм
