### ISSUE TITLE
Верстка страницы "Регистрация пользователя"

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#38]
# Полученная страница регистрации
![image](https://user-images.githubusercontent.com/83533847/125760252-3fefdc25-918f-4f63-ace3-c71f3acdbcaa.png)

# Ссылки
План #3 
User Story #5 
Макет #24
Дизайн #36

---
 # Срок

**Comment by Nastasitze** [comment]
nice

**Comment by Nastasitze** [comment]
> nice

very nice

**Comment by YuriSilenok** [comment]
перенесено в #48
