### ISSUE TITLE
Проверить UX для страницы "Нужно проверить"

### ISSUE THREAD

**Issue by Nastasitze** [YuriSilenok/self-checking#44]
Проверить прототип страницы[ "Нужно проверить"](https://github.com/YuriSilenok/self-checking/issues/25).

**Comment by YuriSilenok** [comment]
Нам не нужны задачи на проверку UX, для того что бы запросить проверку, нужно в задаче на разработку UX написать комментарий что требуется проверка и назначиь ответсвенных за этой
