### ISSUE TITLE
Заголовок и меню

### ISSUE THREAD

**Issue by Nastasitze** [YuriSilenok/self-checking#45]
# User Story

Я как студент/преподаватель хочу иметь возможность перемещаться по персональным разделам сайта, для того чтобы не запоминать адреса сайта.

Критерии приемки:
- Для преподавателя отображаются следующие пункты меню
  - Мои дисциплины
  - Ожидает проверки
- Для студента отображаются следующие пункты меню:
  - Мои задания
  - Ожидает проверки
- Меню отображается в заголовке страницы
- Меню отображается для авторизованного пользователя
- В меню отображается Имя и Фамилия пользователя

# UX

![2021-07-19 (2)](https://user-images.githubusercontent.com/81413003/126149683-37e89258-a2e7-41fb-b19b-1496f8b5770f.png)

# UI

![image](https://user-images.githubusercontent.com/83533847/126606717-7b3f1c1d-9727-4fc9-9150-3996832b4890.png)

**Comment by YuriSilenok** [comment]
Обратите внимание, я добавил User Story, проверьте его

**Comment by Nastasitze** [comment]
@YuriSilenok , в user story будем прописывать про элемент "Приветствие", который присутствует в UX (example - "Добро пожаловать, студент( преподаватель )") ? А к остальной части вопросов нет.

**Comment by YuriSilenok** [comment]
Вопрос хороший, но @ValeriSavvva была против размещения информации там, @ValeriSavvva поясните, где вы ожидаете увидеть приветствие?

**Comment by YuriSilenok** [comment]
переместил задачу в User Story, так как у нас остались по ней вопросы.

**Comment by ValeriSavvva** [comment]
@YuriSilenok @Nastasitze ожидаю замечаний

**Comment by Nastasitze** [comment]
nice, I agree with everything

**Comment by YuriSilenok** [comment]
Если преподаватель уходит со страницы "Мои дисциплины" на страницу "Список тем", должен ли пункт меню "Мои дисциплины" оставаться жирным? Ананлогичные вопросы к остальным страницам, в том числе у студента.

**Comment by Nastasitze** [comment]
> Если преподаватель уходит со страницы "Мои дисциплины" на страницу "Список тем", должен ли пункт меню "Мои дисциплины" оставаться жирным? Ананлогичные вопросы к остальным страницам, в том числе у студента.

Это надо будет обсудить. Есть сомнения на этот счёт, но если отвечать быстро, то я бы не стала выделять пункт меню "Мои дисциплины" , когда пользователь на странице "Список тем".

**Comment by YuriSilenok** [comment]
@ValeriSavvva твое мнение решающее, как скажешь, так и будет

**Comment by Nastasitze** [comment]
> > Если преподаватель уходит со страницы "Мои дисциплины" на страницу "Список тем", должен ли пункт меню "Мои дисциплины" оставаться жирным? Ананлогичные вопросы к остальным страницам, в том числе у студента.
> 
> Это надо будет обсудить. Есть сомнения на этот счёт, но если отвечать быстро, то я бы не стала выделять пункт меню "Мои дисциплины" , когда пользователь на странице "Список тем".

Но, с другой стороны, логично выделить , так как одно страница подчинена другой

**Comment by ValeriSavvva** [comment]
> @ValeriSavvva твое мнение решающее, как скажешь, так и будет

Я считаю, что выделение при уходе на страницу, отличную от контекста наших двух вкладок-закладок, надо снять.

**Comment by YuriSilenok** [comment]
> контекста

что ты называешь контекстом, потому что список тем находится в контексте дисциплины, а список дисциплин и есть наш пункт меню?

**Comment by YuriSilenok** [comment]
Для этой задачи будет создал пулл реквест, что бы обозначить проблемы с кодом
