### ISSUE TITLE
Список дисциплин

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#49]
# User Story
Я как преподаватель хочу иметь возможность просматривать список дисциплин, чтобы знать какие дисциплины уже мной созданы, а так же иметь доступ к функциям редактирования и добавления дисциплины

**Критерии приемки:**
- Список дисциплин отображается в виде таблицы с полями:
  - Название дисциплины
- Список дисциплин состоит только из тех дисциплин, которые я сам создал
- Рядом со списком дисциплин есть элемент управления, позволяющий открыть страницу по добавлению дисциплины
- Название страницы не отображается. Вместо этого надпись "Мои дисциплины" имеет шрифт bold

# UX
Подробнее в [**Figma**](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

[Просьба ознакомится с основными требованиями к UX](https://github.com/YuriSilenok/self-checking/blob/dev/documentation/UX.md)

![2021-07-20 (6)](https://user-images.githubusercontent.com/81413003/126312569-84cb1603-f9a1-496e-84a3-02af0dac598b.png)

### Поведение страницы при добавлении новой дисциплины
При добавлении новой дисциплины блок с полем ввода новой дисциплины и блок с таблицей из существующих дисциплин автоматически центруется по осям _**ox**_ & **_oy_** : 
1) Таблица состоит из 1-ой дисциплины (допустим там что-то написано):
![2021-07-20 (10)](https://user-images.githubusercontent.com/81413003/126313253-d052e1de-d149-41ce-a68c-f275d37e953c.png)

2) Таблица состоит из 6 дисциплин (допустим и тут что-то написано):
![2021-07-20 (9)](https://user-images.githubusercontent.com/81413003/126313198-c81e3f25-14e4-4189-9ffb-d87c5dfd8ac1.png)

# UI 
![image](https://user-images.githubusercontent.com/83533847/126602603-062e1818-370a-49f3-8c4e-d123d4c12c7d.png)

**Comment by Nastasitze** [comment]
@YuriSilenok & @ValeriSavvva please check new UX.

**Comment by YuriSilenok** [comment]
Название страницы

**Comment by ValeriSavvva** [comment]
Все так

**Comment by YuriSilenok** [comment]
В требованиях не указано, должно ли отображаться название страницы или нет

**Comment by YuriSilenok** [comment]
не нужно бросать мне задачу, если она не принята в пулл реквесте

**Comment by YuriSilenok** [comment]
Реализовано в рамках #63
