### ISSUE TITLE
Список тем

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#50]
# User Story
Я как преподаватель хочу иметь возможность просматривать список тем дисциплин, для того чтобы управлять своими курсами.

Критерии приемки:
- Список тем отображается в виде таблицы с полями:
  - Название
- Список тем состоит только из тех тем, которые относятся к выбранной дисциплине
- Рядом со списком тем есть элемент управления, позволяющий открыть страницу по добавлению темы
- Когда мы уходим на страницу "Список тем", пункты меню "Мои дисциплины" и "Ожидает проверки" перестают быть выделенными
- Названием страницы является компонент, в котором будет указано название какой-то дисциплины
- При отсутствии тем на экране появится сообщение с соответствующей информацией: "На данный момент не создано ни одной  темы."

При проектировании учесть #11

# UX
### Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).
![image](https://user-images.githubusercontent.com/83533847/132252667-a7099fdc-442d-4db8-9887-0e296a2167e1.png)

### При добавлении участника из существующего списка преподавателю нужно нажать на стрелку рядом со списком, тогда выпадающий список расширится и примет такой вид:

![image](https://user-images.githubusercontent.com/83533847/132252719-0a25eb92-fd4b-4b45-b106-8d581812a9e6.png)

### Кроме этого, если до этого преподаватель никогда не создавал тем для той или иной дисциплины, то на странице появится сообщение об этом:
![image](https://user-images.githubusercontent.com/83533847/132252697-9a5578a8-cd9f-4d60-8043-491d6b3a2cbc.png)

### По мере добавления новых тем, таблица с ними будет расширятся. Стоит заметить, что при расширении таблицы отступы между контейнерами меняться не будут. Меняются толь 2-а контейнера: BODY & Контейнер с таблицей.
![image](https://user-images.githubusercontent.com/83533847/132368007-672d0bf7-0bfe-4205-9e41-68b2232cfc75.png)

# UI 

![image](https://user-images.githubusercontent.com/83533847/132251707-8ce4a98f-94e3-4c97-bb97-db0d9f9b9425.png)
![image](https://user-images.githubusercontent.com/83533847/132251709-b4cc9d60-129c-48ce-a096-d4342a5a7b51.png)

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok , please check new UX.

**Comment by ValeriSavvva** [comment]
Все хорошо

**Comment by ValeriSavvva** [comment]
@YuriSilenok @Nastasitze

**Comment by Nastasitze** [comment]
@ValeriSavvva  so nice, i into this design 👍

**Comment by YuriSilenok** [comment]
@ValeriSavvva почему на твоих UI мы студенту назначаем задание, а не дисциплину? на UX не так.
@Nastasitze будь внимательней при проверке

**Comment by ValeriSavvva** [comment]
> # User Story
> Я как преподаватель хочу иметь возможность просматривать список тем дисциплин, для того чтобы управлять своими курсами.
> 
> Критерии приемки:
> 
> * Список тем отображается в виде таблицы с полями:
>   
>   * Название
> * Список тем состоит только из тех тем, которые относятся к выбранной дисциплине
> * Рядом со списком тем есть элемент управления, позволяющий открыть страницу по добавлению темы
> * Когда мы уходим на страницу "Список тем", пункты меню "Мои дисциплины" и "Ожидает проверки" перестают быть выделенными
> * Названием страницы является компонент, в котором будет указано название какой-то дисциплины
> 
> При проектировании учесть #11
> 
> # UX
> ### Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).
> ![вапфщ](https://user-images.githubusercontent.com/81413003/126516159-788e934f-88cb-4ea1-a2b8-239fde872d9e.png)
> 
> ### При добавлении участника из существующего списка преподавателю нужно нажать на стрелку рядом со списком, тогда выпадающий список расширится и примет такой вид:
> ![2021-07-21 (3)](https://user-images.githubusercontent.com/81413003/126516200-aaa16053-27ec-4275-88de-0795e7f72465.png)
> 
> ### Кроме этого, если до этого преподаватель никогда не создавал тем для той или иной дисциплины, то на странице появится сообщение об этом:
> ![2021-07-21 (2)](https://user-images.githubusercontent.com/81413003/126516787-8659c28d-ab6b-4e1f-84ca-bd690231ca6d.png)
> 
> ### По мере добавления новых тем, таблица с ними будет расширятся. Стоит заметить, что при расширении таблицы отступы между контейнерами меняться не будут. Меняются толь 2-а контейнера: BODY & Контейнер с таблицей.
> ![2021-07-21 (1)](https://user-images.githubusercontent.com/81413003/126517252-9b65d21e-97aa-498f-b878-817a2e950aed.png)
> 
> # UI
> ![2021-07-30_15-26-22](https://user-images.githubusercontent.com/81413003/127652969-78f90dea-dd09-46dc-9e27-a103930f8c89.png)
> ![2021-07-30_15-27-23](https://user-images.githubusercontent.com/81413003/127652978-df0d61d5-e319-49e0-a1f4-e80dc76b942d.png)

**Comment by Nastasitze** [comment]
@ValeriSavvva & @YuriSilenok , была добавлена формулировка сообщения при отсутствии тем.

**Comment by YuriSilenok** [comment]
Пойдет
