### ISSUE TITLE
Список заданий

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#51]
# User Story
Я как преподаватель хочу иметь возможность просматривать список заданий, для того чтобы управлять своими курсами.

Критерии приемки:
- Список заданий отображается в виде таблицы с полями:
  - Название
  - Количество проверок
- Список задач состоит только из тех задач, которые относятся к выбранной теме
- Рядом со списком заданий есть элемент управления, позволяющий открыть страницу по добавлению требований
- Когда мы уходим на страницу "Список заданий", пункты меню "Мои дисциплины" и "Ожидает проверки" перестают быть выделенными
- Названием страницы является компонент, в котором будет указано название какой-то темы
- При отсутствии задач на экране появится сообщение с соответствующей информацией: "На данный момент не создано ни одной задачи."

# UX
Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

[Просьба ознакомится с основными требованиями к UX](https://github.com/YuriSilenok/self-checking/blob/dev/documentation/UX.md)

### 1) Пользователь-преподаватель ещё не создал ни одного задания для той или иной дисциплины , в той или иной теме данной дисциплины. При этом на странице появляется сообщение, контейнер которой имеет отступ (отступ регулирует UI @ValeriSavvva ) от контейнера с добавлением новой задачи.:
![2021-07-22 (4)](https://user-images.githubusercontent.com/81413003/126617063-99a6c86a-b2e1-4754-9aec-5c72d69a6898.png)

### 2) Пользователь-преподаватель уже создавал какие-то задачи. В этом случае вместо сообщения появляется таблица, контейнер которой имеет отступ (отступ регулирует UI @ValeriSavvva ) от контейнера с добавлением новой задачи.
![2021-07-22 (5)](https://user-images.githubusercontent.com/81413003/126617074-564ba248-543a-47cc-98d2-f4164f73adbf.png)

### По мере добавления новых заданий таблица будет расширяться вниз, расширяя контейнеры BODY и контейнер с самой таблицей. Кроме этого, отступ ( или его отсутствие) не изменяется. *Имеется в виду отступ от контейнера с добавлением новой задачи*
![2021-07-22 (6)](https://user-images.githubusercontent.com/81413003/126617090-3a3d6230-8189-4588-8139-afa5c8aa7422.png)

# UI 
![2021-07-26_17-55-08](https://user-images.githubusercontent.com/81413003/127010864-d69992b5-df4c-4aa8-8843-0645358755f7.png)
![2021-07-26_17-57-29](https://user-images.githubusercontent.com/81413003/127011018-cc8df390-5b2b-4709-abd8-ab3fc37a4e63.png)

**Comment by Nastasitze** [comment]
@ValeriSavvva  & @YuriSilenok , please check new UX/

**Comment by ValeriSavvva** [comment]
меня все устраивает

**Comment by ValeriSavvva** [comment]
@YuriSilenok @Nastasitze

**Comment by YuriSilenok** [comment]
Почему список заданий находжится в "Ожидает проверки"?

**Comment by YuriSilenok** [comment]
Почему у нас два поля "Название задачи"?

**Comment by Nastasitze** [comment]
@YuriSilenok & @ValeriSavvva  , please check new updates for UI

**Comment by YuriSilenok** [comment]
если мы уходим на список заданий, пункт меню мои дисциплины перестает быть выделенным?

**Comment by Nastasitze** [comment]
> если мы уходим на список заданий, пункт меню мои дисциплины перестает быть выделенным?

Думаю , так проще показать , что это новая вкладка , которая не относится ни к странице "Ожидают проверок", ни к странице "Мои работы"

**Comment by Nastasitze** [comment]
Единственное, что не очень удобно, так это количество страниц, которых нет в меню быстрого доступа

**Comment by YuriSilenok** [comment]
> Единственное, что не очень удобно, так это количество страниц, которых нет в меню быстрого доступа

мы не можем просто так перейти на список тем, так как нужен контекст, нужно знать к какой дисциплине отностяся эти темы

**Comment by Nastasitze** [comment]
@ValeriSavvva  & @YuriSilenok  , была добавлена формулировка сообщения при отсутствии задач.

**Comment by YuriSilenok** [comment]
Мне норм
