### ISSUE TITLE
Список требований

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#52]
Я как преподаватель хочу иметь возможность просматривать список требований, для того чтобы управлять своими курсами.

Критерии приемки:
- Список требований отображается в виде списка требований
- Список требований состоит только из тех требований, которые относятся у задаче
- Рядом со списком требований есть элемент управления, позволяющий открыть страницу по добавлению требования
- Когда мы уходим на страницу "Список требований", пункты меню "Мои дисциплины" и "Ожидает проверки" перестают быть выделенными
- Названием страницы является компонент, в котором будет указано название какой-то задачи
- При отсутствии требований на экране появится сообщение с соответствующей информацией: "У этой задачи пока нет никаких требований."

# UX
Подробнее в [Figma](https://www.figma.com/file/jo7JCWO6fNQ85TyZxemGlN/Untitled?node-id=15%3A10).

[Просьба ознакомится с основными требованиями к UX](https://github.com/YuriSilenok/self-checking/blob/dev/documentation/UX.md)
### Страница "Список требований" имеет 2 основных состояния:
1. Пользователь-преподаватель ещё не создал ни одного требования для той или иной задачи , в той или иной теме какой-то дисциплины. При этом на странице появляется сообщение, контейнер которой имеет отступ (отступ регулирует UI @ValeriSavvva ) от контейнера с добавлением нового требования:
![2021-07-23](https://user-images.githubusercontent.com/81413003/126782655-5662125a-0c9d-44b8-a4a1-0d5ca1616b40.png)

2. Пользователь-преподаватель уже создавал какое-то требование. В этом случае вместо сообщения появляется таблица, контейнер которой имеет отступ (отступ регулирует UI @ValeriSavvva ) от контейнера с добавлением нового требования:
![2021-07-23 (1)](https://user-images.githubusercontent.com/81413003/126782785-9d9ee82a-27a0-4cf3-a896-a4855c884c53.png)
По мере добавления новых требований таблица будет расширяться вниз, расширяя контейнеры BODY и контейнер с самой таблицей. Кроме этого, отступ ( или его отсутствие) не изменяется. *Имеется в виду отступ от контейнера с добавлением нового требования*
![2021-07-23 (2)](https://user-images.githubusercontent.com/81413003/126782824-c2eae85e-91bc-425b-848f-e65d0f6ebbfe.png)

# UI 
![image](https://user-images.githubusercontent.com/83533847/128864430-2631b6da-c32c-4441-8fe3-a9b449d9971f.png)
![image](https://user-images.githubusercontent.com/83533847/132252886-b9c6ad55-bc1d-4090-ab3b-502ace2ff1d6.png)

**Comment by Nastasitze** [comment]
@ValeriSavvva  & @YuriSilenok , pleas check new UX

**Comment by ValeriSavvva** [comment]
![image](https://user-images.githubusercontent.com/83533847/126944033-e0db68d5-c085-4839-999b-11a1241ed8fa.png)
Предлагаю сделать структуру такой

**Comment by YuriSilenok** [comment]
Как определить для какого задания эти требования?

**Comment by ValeriSavvva** [comment]
я имела ввиду что название задания останется, поменяется внешний вид добавления, нам же важно сохранить эквивалентное расположение кнопок в UI и UX

**Comment by YuriSilenok** [comment]
расположение элеметов по добавлению требования выглядит хорошо

**Comment by ValeriSavvva** [comment]
@YuriSilenok  @Nastasitze

**Comment by Nastasitze** [comment]
approved

**Comment by YuriSilenok** [comment]
Где название страницы?

**Comment by ValeriSavvva** [comment]
> Где название страницы?

Разве название задачи не является названием страницы?

**Comment by ValeriSavvva** [comment]
@YuriSilenok  @Nastasitze Я считаю что здесь вполне из контекста понятно название страницы из названия задачи

**Comment by YuriSilenok** [comment]
Думаю можно так оставить, название задачи и будет названием страницы

**Comment by Nastasitze** [comment]
@ValeriSavvva  & @YuriSilenok  , была добавлена формулировка сообщения при отсутствии требований.

**Comment by YuriSilenok** [comment]
Это сообщение отображается для преподавателя и думаю лучше использовать шаблон фразы как в #51
