### ISSUE TITLE
Граница между названиями столбцов не отображается во всех таблицах.

### ISSUE THREAD

**Issue by ValeriSavvva** [YuriSilenok/self-checking#54]
Граница между названиями столбцов не отображается на следующих страницах:

- #49
- #50
- #51
- #52
- #34 
- #15 
- #16 

**Фактический результат** 
![image](https://user-images.githubusercontent.com/83533847/127516553-898ec401-eea3-4b6b-b244-cb02fa19b57f.png)

**Ожидаемый результат** 
![image](https://user-images.githubusercontent.com/83533847/127516811-77b80304-3d10-409f-bef9-acd0722605bb.png)

**Comment by ValeriSavvva** [comment]
Данного бага не возникает в процессе верстки

**Comment by YuriSilenok** [comment]
баг поднят ошибочно
