### ISSUE TITLE
Презентация версии 0.1

### ISSUE THREAD

**Issue by YuriSilenok** [YuriSilenok/self-checking#62]
- Презентация должна быть выполнена в гкгл-презентациях
- Показать чем это выгодно преподавателю
- Показать как это можно использовать
- Как это связано с СДО
- По возможности зафиксировать отзыв

**Comment by Nastasitze** [comment]
1/ [Link to google docs --> ](https://docs.google.com/presentation/d/1NcRVOGMT65Yll7N7Dm8vug1ULjxRRJWOHV6UIE4vQRU/edit?usp=sharing)

2/ [File to download (.pdf) ](https://github.com/YuriSilenok/self-checking/files/7272875/default.pdf)

3/  Reviews : 1) The essence of the system is poorly disclosed. One of the guests didn't understand how it's works/
2)  Slied 9 - terrible diagram (too much, bro, it was too much)
3) Unfished work.

**Comment by YuriSilenok** [comment]
Презентация будет доделываться?

**Comment by Nastasitze** [comment]
@YuriSilenok , нет, так как лучше будет сделать для последующих версий новую презентацию

**Comment by YuriSilenok** [comment]
Эта презентация для версии 0,1, это значит что для создания презентации на другие версии будут другие задачи. По этой презентации для версии 0.1 работы завершены?

**Comment by Nastasitze** [comment]
@YuriSilenok, да , работы закончины

**Comment by YuriSilenok** [comment]
Есть ли какие-то причины по которой эта задача не закрыта?

**Comment by Nastasitze** [comment]
веской причины нет, просто руки не дошли
сейчас закрою
